spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: servidor
          uri: lb://SERVIDOR-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/servidor/**
        - id: departamento
          uri: lb://DEPARTAMENTO-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/departamento/**
server:
  port: 9999
eureka:
  client:
    service-url:
      default-url: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.intance_id:${random.value}}
